AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "General Configuration"
        Parameters:
          - ServiceName
      -
        Label:
          default: "NetWork Configuration"
        Parameters:
          - VpcId
          - SubnetId
Parameters:
  ServiceName:
    Description: "input your ServiceName."
    Type: String
    Default: "sample-app"
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: Select a VPC that allows instances access to the Internet.
  SubnetId:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Select at two subnets in your selected VPC.
Mappings:
  Region2ELBAccountId:
    us-east-1:
      AccountId: '127311923021'
    us-east-2:
      AccountId: 033677994240
    us-west-1:
      AccountId: 027434742980
    us-west-2:
      AccountId: '797873946194'
    ap-northeast-1:
      AccountId: '582318560864'
    ap-northeast-2:
      AccountId: '600734575887'
    ap-southeast-1:
      AccountId: '114774131450'
    ap-southeast-2:
      AccountId: '783225319266'
Resources:         
# ------------------------------------------------------------#
#  ECS Cluster
# ------------------------------------------------------------#         
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub "${ServiceName}-cluster"
# ------------------------------------------------------------#
#  S3 (ALB Log Bucket)
# ------------------------------------------------------------#         
  LBLogBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ServiceName}-accesslog"
      AccessControl: LogDeliveryWrite
      LifecycleConfiguration:
        Rules:
        - Id: GlacierRule
          Prefix: glacier
          Status: Enabled
          ExpirationInDays: '365'
          Transitions:
            - TransitionInDays: '30'
              StorageClass: Glacier

  LogsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LBLogBucket
      PolicyDocument:
        Version: '2008-10-17'
        Statement:
        - Sid: ELBAccessLogs20130930
          Effect: Allow
          Resource: !Sub "arn:aws:s3:::${LBLogBucket}/alb_log/AWSLogs/${AWS::AccountId}/*"
          Principal:
            AWS: !FindInMap [Region2ELBAccountId, !Ref 'AWS::Region', AccountId]
          Action: ['s3:PutObject']