AWSTemplateFormatVersion: '2010-09-09'
Resources:
# ------------------------------------------------------------#
#  ECS Role
# ------------------------------------------------------------#
  ECSRole:
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "ecs.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: /

  ECSTaskRolePolicies: 
    Type: "AWS::IAM::Policy"
    Properties: 
      PolicyName: "ECSTaskRole"
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Action: "*"
            Resource: "*"
      Roles: 
        - !Ref ECSRole
# ------------------------------------------------------------#
#  ECS Task Role
# ------------------------------------------------------------#
  ECSTaskExecutionRole:
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "ecs-tasks.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: /

  ECSTaskRolePolicies: 
    Type: "AWS::IAM::Policy"
    Properties: 
      PolicyName: "ECSTaskRole"
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Action: "*"
            Resource: "*"
      Roles: 
        - !Ref ECSTaskExecutionRole
# ------------------------------------------------------------#
#  AutoScale Role
# ------------------------------------------------------------#         
  AutoScalingRole: 
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "application-autoscaling.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: /
      
  AutoScalingPolicies: 
    Type: "AWS::IAM::Policy"
    Properties: 
      PolicyName: "AutoScalingRole"
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Action: "*"
            Resource: "*"
      Roles: 
        - !Ref AutoScalingRole