AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ECSTaskRole: 
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "ecs-tasks.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/system/"
  ECSTaskRolePolicies: 
    Type: "AWS::IAM::Policy"
    Properties: 
      PolicyName: "ECSTaskRole"
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Action: "*"
            Resource: "*"
      Roles: 
        - !Ref ECSTaskRole
  AutoScalingRole: 
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "application-autoscaling.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/system/"
  AutoScalingPolicies: 
    Type: "AWS::IAM::Policy"
    Properties: 
      PolicyName: "AutoScalingRole"
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Action: "*"
            Resource: "*"
      Roles: 
        - !Ref AutoScalingRole